### ISSUE TITLE
Attack of the error boxes!

### ISSUE THREAD

**Issue by SuperDX** [stuie382/Tournament-Database#2]
Hey Dude,

Hope you are keeping well. I have just been testing the tournament App & made sure I had Java 1.8.0 but I seem to be getting error messages everytime I try to go into anything. 

When clicking on View all in the players section it freezes &  I get this error –  error encountered viewing all players . See the log for details.

When trying to add a new player I type in the player’s name (example David Cross) It then freezes & then I get the below – error encountered adding a new player . See the log for details. 

When clicking on view all for Manage Tournaments it freezes then gives me the below – error encountered viewing all players . See the log for details.

I tried logging a new tournament. When clicking on Add tournament the pop up screen came up to type in the tournament name I added 23112012. Once I clicked ok the screen freezes and I then get the below –  error encountered adding a new tournament .Please see the log for details.

When clicking on Play a Game the system freezes and I then get the below error –  Please see the log for details

I have the screen prints if you need them but wasn't sure if this is the App or my computer so if there is anything else you need me to check this end please let me know.
Cheers Dude

**Comment by stuie382** [comment]
Hey, that sounds a bit odd. Send me the log file and I'll have a look. What do you get when you run the following command in the cmd window 'java -version' ' without the ' marks.

**Comment by SuperDX** [comment]
Hey Dude,

Got your text. Here is the file I have of the issues I took down. Hope they help.

:)

**Comment by stuie382** [comment]
Hey Dave,

In the directory with the application, there should be two files - one called tourny_log.txt, and one called derby.log. Can you attach and send those please. They are the log files that the error messages are talking about :)

Without seeing those, this sounds like either something unusual with your laptop setup, or you need a more up to date version of Java 8. I had tried running it on a number of different machines aside from my dev one and it worked ok. Once I get those files from the directory I should be able to let you know, or you can read them yourself and try and figure it out :)

**Comment by SuperDX** [comment]
Hey Stu,

I think I have attached the right files. Wasn't sure which one of the log ones you needed.

Hope this helps

Dave :)

Wed Jan 28 18:57:57 GMT 2015 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Database 'Tournament' not found.
    at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
    at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
    at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
    at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
    at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:208)
    at org.apache.derby.impl.tools.ij.ij.dynamicConnection(Unknown Source)
    at org.apache.derby.impl.tools.ij.ij.ConnectStatement(Unknown Source)
    at org.apache.derby.impl.tools.ij.ij.ijStatement(Unknown Source)
    at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)
    at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)
    at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)
    at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)
    at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)
    at org.apache.derby.tools.ij.main(Unknown Source)
Caused by: java.sql.SQLException: Database 'Tournament' not found.
    at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
    ... 23 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'Tournament' not found.
    at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
    at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
    at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
    at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
    at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
    at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:208)
    at org.apache.derby.impl.tools.ij.ij.dynamicConnection(Unknown Source)
    at org.apache.derby.impl.tools.ij.ij.ConnectStatement(Unknown Source)
    at org.apache.derby.impl.tools.ij.ij.ijStatement(Unknown Source)
    at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)
    at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)
    at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)
    at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)
    at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)
    at org.apache.derby.tools.ij.main(Unknown Source)
============= end nested exception, level (1) ===========

## Cleanup action completed

## Wed Jan 28 18:58:28 GMT 2015: Shutting down Derby engine

# *************************************************************************

# **\*              DO NOT TOUCH FILES IN THIS DIRECTORY!                ***

# **\* FILES IN THIS DIRECTORY ARE USED BY THE DERBY DATABASE RECOVERY   ***

# **\* SYSTEM. EDITING, ADDING, OR DELETING FILES IN THIS DIRECTORY      ***

# **\* WILL CAUSE THE DERBY RECOVERY SYSTEM TO FAIL, LEADING TO          ***

# **\* NON-RECOVERABLE CORRUPT DATABASES.                                ***

# *************************************************************************
